# Generated by Django 3.1 on 2024-11-29 21:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumnos',
            fields=[
                ('ALUMRUT', models.CharField(default=1, max_length=12, primary_key=True, serialize=False)),
                ('ALUMNOMBRE', models.CharField(max_length=15)),
                ('ALUMAPATERNO', models.CharField(max_length=15)),
                ('ALUMAMATERNO', models.CharField(max_length=15)),
                ('ALUMDIRECCION', models.CharField(max_length=60)),
                ('ALUMEMAIL', models.CharField(max_length=40)),
                ('ALUMNFONO', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ciudades',
            fields=[
                ('CIUCODIGO', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('CIUNOMBRE', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_cursos',
            fields=[
                ('TIPCURCODIGO', models.IntegerField(default=1, max_length=6, primary_key=True, serialize=False)),
                ('TIPCURNOMBRE', models.CharField(max_length=15)),
                ('TIPCURVALOR', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('USULOGIN', models.CharField(default=1, max_length=15, primary_key=True, serialize=False)),
                ('USUPASSWORD', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='sucursales',
            fields=[
                ('SUCCODIGO', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('SUCNOMBRE', models.CharField(max_length=20)),
                ('CIUCODIGO', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appBD.ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='matriculas',
            fields=[
                ('MATNUMERO', models.IntegerField(default=1, max_length=11, primary_key=True, serialize=False)),
                ('MATFECHA', models.DateField(default=django.utils.timezone.now)),
                ('ALUMRUT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appBD.alumnos')),
                ('SUCCODIGO', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appBD.sucursales')),
                ('TIPCURCODIGO', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appBD.tipo_cursos')),
            ],
        ),
    ]
