# Generated by Django 3.1.1 on 2024-11-26 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ALUMRUT', models.CharField(max_length=12)),
                ('ALUMNOMBRE', models.CharField(max_length=15)),
                ('ALUMAPATERNO', models.CharField(max_length=15)),
                ('ALUMAMATERNO', models.CharField(max_length=15)),
                ('ALUMDIRECCION', models.CharField(max_length=60)),
                ('ALUMEMAIL', models.CharField(max_length=40)),
                ('ALUMNFONO', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ciudades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIUNOMBRE', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='matriculas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MATNUMERO', models.SmallIntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIPCURNOMBRE', models.CharField(max_length=15)),
                ('TIPCURVALOR', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USULOGIN', models.CharField(max_length=15)),
                ('USUPASSWORD', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='sucursales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUCNOMBRE', models.CharField(max_length=20)),
                ('CIUCODIGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBD.ciudades')),
            ],
        ),
    ]
